### ISSUE TITLE
[help] error min js

### ISSUE THREAD

**Issue by wiloke1** [fizker/minifier#28] opened 2017-11-04 05:03 UTC
undefined:1625
    throw new JS_Parse_Error(message, filename, line, col, pos);
    ^
SyntaxError: Unexpected token: punc (.)
    at JS_Parse_Error.get (eval at <anonymous> (F:\Project\node_modules\minifier\node_modules\uglify-js\tools\node.js:27:1), <anonymous>:86:23)
events.js:182
      throw er; // Unhandled 'error' event

**Comment by fizker** [comment] 2017-11-09 09:08
This sounds like a duplicate of #19, in that the version of uglifyjs used only supports ES5 syntax, and it sounds like your code might include rest syntax (`function a(...args)`

**Comment by long-hp** [comment] 2018-01-30 18:48
tks @fizker

**Closed** 2018-01-30 21:14 UTC
